#!/usr/bin/env bash

set -e

PYVER=
while [ "${1:0:1}" == "-" ]; do
    case $1 in
        --python)
            PYVER=${2:?--python requires an argument}
            shift 2;;
        --python=*)
            PYVER=${1#*=}
            shift 1;;
        -*)
            echo "Unknown parameter \"$1\""
            exit 1
     esac
done

PREFIX=/Library/Frameworks/Python.framework/Versions/${PYVER:?}
PYTHON="$PREFIX"/bin/python$PYVER

"$PYTHON" -m venv "$@"
