#!/usr/bin/env bash


__PLIST_HEADER='
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
'
__PLIST_TAIL='
</array>
</plist>
'

__INSTALL_CHOICE_TEMPLATE='
    <dict>
        <key>attributeSetting</key>
        <integer>SELECTED</integer>
        <key>choiceAttribute</key>
        <string>selected</string>
        <key>choiceIdentifier</key>
        <string>CHOICE_IDENTIFIER</string>
    </dict>
'

choice-select() {
    local identifier=${1:?}
    local value=${2:?}
    local part=$(m4 -DSELECTED="$value" -DCHOICE_IDENTIFIER="$identifier" \
                 <<< "$__INSTALL_CHOICE_TEMPLATE")
    printf "%s\n" "$part"
}

CACHEDIR=${CACHEDIR:-"$HOME/Library/Caches/vagabond"}

install-python-framework() {
    local version=${1:?}
    local pyver=${version%.*}
    local pkgname=python-${version}-macosx10.6.pkg
    local pkgurl=https://www.python.org/ftp/python/${version}/${pkgname}
    local pkg="$CACHEDIR/$pkgname"

    mkdir -p "$CACHEDIR"
    if [ ! -f "$pkg" ]; then
        curl -fSL -o "$pkg" "$pkgurl"
    fi

    printf "%s" "$__PLIST_HEADER" > choices.plist
    # Do not install Idle.app, PythonLauncher.app, ...
    local disable=( \
        org.python.Python.PythonApplications-${pyver} \
        org.python.Python.PythonDocumentation-${pyver} \
        org.python.Python.PythonProfileChanges-${pyver} \
    )

    for choice in ${disable[*]}
    do
        choice-select $choice 0 >> choices.plist
    done
    printf "%s" "$__PLIST_TAIL" >> choices.plist

    installer -pkg "$pkg" \
              -showChoicesAfterApplyingChangesXML choices.plist \
              -target / > ChoiceChanges.plist

    sudo installer -pkg "$pkg" \
                   -applyChoiceChangesXML ChoiceChanges.plist \
                   -target /
    rm choices.plist ChoiceChanges.plist
}

install-python-framework ${1:?"Need a python version (major.minor.micro)"}